version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_passwort
      MYSQL_DATABASE: db
      MYSQL_USER: web
      MYSQL_PASSWORD: fgth
    volumes:
      - ./.mysql:/var/lib/mysql
    ports:
      - "3306:3306"
